### ISSUE TITLE
Add Dollar-Sign to path

### ISSUE THREAD

**Issue by mdix** [premasagar/tim#14]
You should consider adding the dollar sign to 

`path    = "[a-z0-9_][\\.a-z0-9_]*", // e.g. config.person.name` 
like
`path    = "[a-z0-9_$][\\.a-z0-9_$]*", // e.g. config.person.name` 

because, for instance youtube, returns something like this:

`{feed:{entry: [{id:{$t: 'just a test'}, title:{$t: 'just the title'}}]}};`

which cannot be parsed by tinytim like we'd expect:

`{{feed.entry.0.title.$t}}`

Thanks for your trouble and kind regards 
Marc

**Comment by premasagar** [comment]
Thanks for this, @mdix. Fixed in 812bca6477188f117b65e515267eeefec6dbdc5f
