### ISSUE TITLE
How to render an array of strings?

### ISSUE THREAD

**Issue by ismasan** [premasagar/tim#20]
Hello. First of all thank you so much for this library.

My question: it is not clear to me how to render an array of strings, example:

``` javascript
tim("{{tags}}<li>{{ ? }}</li>{{/tags}}", {tags: ["tag1", "tag2", "tag3"]})
```

Any advice welcome. I'll be happy to document this in a pull request.

Regards.

**Comment by aron** [comment]
From looking at the [readme](https://github.com/premasagar/tim#iterating-over-objects).

```
tim("{{tags}}<li>{{_content}}</li>{{/tags}}", {tags: ["tag1", "tag2", "tag3"]})
```

It's not very clear though...

**Comment by ismasan** [comment]
Ah, I didn't realise that works too, since it's documented as "iterating over objects". Thanks.
