### ISSUE TITLE
export to nodejs and AMD loaders

### ISSUE THREAD

**Issue by millermedeiros** [premasagar/tim#8]
right now library assumes the browser environment. it's better to create a wrapper that will avoid creating global variables if an [AMD loader](http://requirejs.org/docs/whyamd.html) is detected and also if running on nodejs...

based on the current implementation it's actually easy to create a wrapper that would run on multiple environments:

``` js
(function(global){

    // YOUR CODE GOES HERE //

    //exports to multiple environments
    if(typeof define === 'function' && define.amd){ //AMD
        define('tim', [], tim);
    } else if (typeof module !== 'undefined' && module.exports){ //node
        module.exports = tim;
    } else { //browser
        //use string because of Google closure compiler ADVANCED_MODE
        global['tim'] = tim;
    }

}(this));
```

for a wrapper that would run on other CJS environments besides nodejs check second example of [this gist](https://gist.github.com/1262861).

**Comment by premasagar** [comment]
Fixed in 1ca52eced9e72ad879170291e2903ea2d6c4fa9c
